export const options = {
    Aerosol: "Aerosol",
    Ampolla: "Ampolla",
    Caja: "Caja",
    Capsula: "Capsula",
    Comprimido: "Comprimido",
    CremaTopica: "Crema topica",
    Emulsion: "Emulsion",
    Frasco: "Frasco",
    FrascosVial: "Frascos Vial",
    GelTopico: "Gel topico",
    Gotas: "Gotas",
    Granulados: "Granulados",
    Inhaladores: "Inhalacion",
    Jarabe: "Jarabe",
    Lata: "Lata",
    Liquido: "Liquido",
    Mezclado: "Mezclado",
    Otico: "Otico",
    Ovulo: "Ovulo",
    ParcheTransdermico: "Parche termico",
    PolvoSuspensionOral: "Polvo para suspension",
    Polvo: "Polvo",
    PolvoEsteril: "Polvo esteril",
    PolvoEsterilReconstituir: "Polvo esteril para reconstituir",
    PolvoLiofilizado: "Polvo liofilizado",
    PolvoReconstituir: "Polvo para reconstituir",
    PolvoSolucionInyectable: "Polvo para solucion inyectable",
    Pomada: "Pomada",
    Pote: "Pote",
    Solucion: "Solucion",
    SolucionInyectable: "Solucion inyectable",
    SolucionNasal: "Solucion nasal",
    SolucionOftalmica: "Solucion oftalmica",
    SolucionOral: "Solucion oral",
    solucionInfusion: "solucion para infusion",
    SolucionInhalar: "Solucion para inhalar",
    SolucionNebulizar: "Solucion para nebulizar",
    SolucionTopica: "Solucion topica",
    Suspension: "Suspension",
    SuspensionInyectable: "Suspension inyectable",
    SuspensionOral: "Suspension oral",
    SuspensiónRectal: "Suspensión rectal",
    Tableta: "Tableta",
    Unguento: "Unguento",
    UnguentoTopica: "Unguento topica",
    Vial: "Vial"
};